 platform :ios, '11.0'

target 'ex2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex2
flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
install_all_flutter_pods(flutter_application_path)

end
